# Generated by Django 5.1.6 on 2025-02-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='height_unit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight_unit',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.activitytype', verbose_name='Тип активности'),
        ),
    ]
