# Generated by Django 5.1.6 on 2025-03-09 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_bodyparameters_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kcal', models.FloatField(blank=True, null=True, verbose_name='Целевые калории (ккал)')),
                ('target_protein', models.FloatField(blank=True, null=True, verbose_name='Целевые белки (г)')),
                ('target_fat', models.FloatField(blank=True, null=True, verbose_name='Целевые жиры (г)')),
                ('target_carb', models.FloatField(blank=True, null=True, verbose_name='Целевые углеводы (г)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цели по КБЖУ',
                'verbose_name_plural': 'Цели по КБЖУ',
            },
        ),
    ]
