services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kilona57
      POSTGRES_DB: Diploma
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d HealthFitDB" ]
      interval: 15s
      retries: 10
      start_period: 60s
      timeout: 10s
    ports:
      - '5434:5432'
    restart: always







