# Generated by Django 5.1.6 on 2025-03-11 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы мышц')),
            ],
            options={
                'verbose_name': 'Группа мышц',
                'verbose_name_plural': 'Группы мышц',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название упражнения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание упражнения')),
                ('difficulty', models.CharField(max_length=50, verbose_name='Сложность упражнения')),
                ('calories_burned', models.PositiveIntegerField(verbose_name='Количество затрачиваемых калорий')),
                ('gif_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на GIF-изображение')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.equipment', verbose_name='Оборудование')),
                ('muscle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.musclegroup', verbose_name='Группа мышц')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
    ]
