# Generated by Django 5.1.6 on 2025-03-11 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сложности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сложности')),
                ('level', models.PositiveIntegerField(help_text='Чем выше число, тем сложнее упражнение', verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Сложность',
                'verbose_name_plural': 'Сложности',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='gif_url_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на GIF-изображение 2'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.difficulty', verbose_name='Сложность'),
        ),
        migrations.CreateModel(
            name='ExerciseGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_name', models.CharField(help_text='Имя файла в папке static/gif', max_length=255, verbose_name='Имя GIF-файла')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifs', to='workouts.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'GIF-изображение',
                'verbose_name_plural': 'GIF-изображения',
            },
        ),
    ]
