# Generated by Django 5.1.6 on 2025-03-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_difficulty_exercise_gif_url_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='gif_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='gif_url_2',
        ),
    ]
