# Generated by Django 5.1.6 on 2025-03-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bodyparameters_height_bodyparameters_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyparameters',
            name='height',
        ),
        migrations.RemoveField(
            model_name='bodyparameters',
            name='weight',
        ),
    ]
